spring.application.name=enterprise-ecommerce
server.port=45230

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.url.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show.sql=true
spring.jpa.open.in.view=false


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:my-very-secure-secret-key-that-is-at-least-32-characters-long}